<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/5/21
 * Time: 9:09
 */

namespace Wap\Controller;
use Think\Controller;

class performanceController extends BaseController
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 当日到账
     */
    public function dayPerformanceList(){
        if(I("post.months")){
            echo 1;exit;
        }
        $type = I("get.type");
        /**
         * 1 部门 2个人
         */
        if($type==2){
            $sql = "select a.performance,d.truename from `qp_employee` as d LEFT JOIN 
(select SUM(`performance`) as performance,employee_id from qp_performance where to_days(compact_time) = to_days(now()) 
GROUP BY employee_id) as a on d.id = a.employee_id order by a.performance desc";
            $list = M()->query($sql);
            $str = "";
            $str1 = "";
            $count = count($list);
            foreach($list as $k=>$v){
                if($count-1>$k){
                    $yeji = $v['performance']/10000;
                    $str .="'{$v['truename']}',";
                    $str1 .= "{$yeji},";
                }elseif ($count-1==$k){
                    $yeji = $v['performance']/10000;
                    $str .="'{$v['truename']}'";
                    $str1 .= "{$yeji}";
                }
            }
            $danwei = "万";
        }else{
            $sql = "select a.performance,d.department from `qp_department` as d LEFT JOIN 
(select SUM(`performance`) as performance,department_id from qp_performance where to_days(compact_time) = to_days(now())
GROUP BY department_id) as a on d.id = a.department_id order by a.performance desc";
            $list = M()->query($sql);
            $str = "";
            $str1 = "";
            $count = count($list);
            foreach($list as $k=>$v){
                if($count-1>$k){
                    $yeji = $v['performance']/10000;
                    $str.="'{$v['department']}',";
                    $str1 .= "{$yeji},";
                }elseif ($count-1==$k){
                    $yeji = $v['performance']/10000;
                    $str.="'{$v['department']}'";
                    $str1 .= "{$yeji}";
                }
            }
            $danwei = "万";
        }
        $this->assign('title','当日到账');
        $this->assign("contro",'day');
        $this->assign('danwei',$danwei);
        $this->assign('str',$str);
        $this->assign('str1',$str1);
        $this->display();
    }
    /**
     * 当月到账
     */
    public function monthPerformanceList(){

        $type = I("get.type");
        /**
         * 1 部门 2个人
         */
        if($type==2){
            if(I("post.months") !="")
            {

                $i_month = I("post.months");

                $arr = explode('-',$i_month);

                $year1 = $arr[0];

                $month1 = $arr[1];

                $day_end = $this->daysInmonth($year1,$month1);

                $i_month_end = $year1.'-'.$month1.'-'.$day_end;

                $i_month_begin = $i_month."-01";

                $sql = "select a.performance,d.truename from `qp_employee` as d LEFT JOIN 
(select SUM(`performance`) as performance,employee_id from qp_performance where compact_time > '$i_month_begin' and compact_time < '$i_month_end'
GROUP BY employee_id) as a on d.id = a.employee_id order by a.performance desc";

            }else{
                $sql = "select a.performance,d.truename from `qp_employee` as d LEFT JOIN 
(select SUM(`performance`) as performance,employee_id from qp_performance where DATE_FORMAT(compact_time, '%Y%m') = DATE_FORMAT(CURDATE(), '%Y%m')
GROUP BY employee_id) as a on d.id = a.employee_id order by a.performance desc";
            }

            $list = M()->query($sql);
            $str = "";
            $str1 = "";
            $count = count($list);
            if(!empty($list)){
                foreach($list as $k=>$v){
                    if($count-1>$k){
                        $yeji = $v['performance']/10000;
                        $str .="'{$v['truename']}',";
                        $str1 .= "{$yeji},";
                    }elseif ($count-1==$k){
                        $yeji = $v['performance']/10000;
                        $str .="'{$v['truename']}'";
                        $str1 .= "{$yeji}";
                    }
                }
            }

            $danwei = "万";
        }else{

            if(I("post.months") !="")
            {

                $i_month = I("post.months");

                $arr = explode('-',$i_month);

                $year1 = $arr[0];

                $month1 = $arr[1];

                $day_end = $this->daysInmonth($year1,$month1);

                $i_month_end = $year1.'-'.$month1.'-'.$day_end;
                $i_month_begin = $i_month."-01";
                $sql = "select a.performance,d.department from `qp_department` as d LEFT JOIN 
(select SUM(`performance`) as performance,department_id from qp_performance where compact_time > '$i_month_begin' and compact_time < '$i_month_end'
GROUP BY department_id) as a on d.id = a.department_id order by a.performance desc";

            }else{
                $sql = "select a.performance,d.department from `qp_department` as d LEFT JOIN 
(select SUM(`performance`) as performance,department_id from qp_performance where DATE_FORMAT(compact_time, '%Y%m') = DATE_FORMAT(CURDATE(), '%Y%m')
GROUP BY department_id) as a on d.id = a.department_id order by a.performance desc";
            }

            $list = M()->query($sql);
            $str = "";
            $str1 = "";
            $count = count($list);
            if(!empty($list)){
                foreach($list as $k=>$v){
                    if($count-1>$k){
                        $yeji = $v['performance']/10000;
                        $str.="'{$v['department']}',";
                        $str1 .= "{$yeji},";
                    }elseif ($count-1==$k){
                        $yeji = $v['performance']/10000;
                        $str.="'{$v['department']}'";
                        $str1 .= "{$yeji}";
                    }
                }
            }

            $danwei = "万";
        }

        $z = date('Y-m');

        $days = '';
        for($i=12;$i>-1;$i--){
            $a = date('Y-m', strtotime("-$i months"));
            if($i_month !=""){
                if($i_month == $a){
                    $days.="<option value='$a' selected='selected'>$a</option>";
                }else{
                    $days.="<option value='$a'>$a</option>";
                }
            }else{
                if($z==$a){
                    $days.="<option value='$a' selected='selected'>$a</option>";
                }else{
                    $days.="<option value='$a'>$a</option>";
                }
            }


        }
        $sel = "<select name='months'>$days</select>";
        //echo $sel;
        $this->assign('title','月度业绩');
        $this->assign("sel_month",$sel);
        $this->assign("contro",'month');
        $this->assign('danwei',$danwei);
        $this->assign('str',$str);
        $this->assign('str1',$str1);
        $this->display('dayPerformanceList');
    }
    /**
     * 当年到账
     */
    public function yearPerformanceList(){
        $type = I("get.type");
        /**
         * 1 部门 2个人
         */
        if($type==2){
            if(I("post.months") !="")
            {

                $i_month = I("post.months");

                $i_month_begin = $i_month."-01-01";

                $i_month_end = $i_month."-12-31";

                $sql = "select a.performance,d.truename from `qp_employee` as d LEFT JOIN 
(select SUM(`performance`) as performance,employee_id from qp_performance where compact_time > '$i_month_begin' and compact_time < '$i_month_end'
GROUP BY employee_id) as a on d.id = a.employee_id order by a.performance desc";

            }else{
                $sql = "select a.performance,d.truename from `qp_employee` as d LEFT JOIN 
(select SUM(`performance`) as performance,employee_id from qp_performance where YEAR(compact_time) = YEAR(now()) 
GROUP BY employee_id) as a on d.id = a.employee_id order by a.performance desc";
            }

            $list = M()->query($sql);
            $str = "";
            $str1 = "";
            $count = count($list);
            if(!empty($list)){
                foreach($list as $k=>$v){
                    if($count-1>$k){
                        $yeji = $v['performance']/10000;
                        $str .="'{$v['truename']}',";
                        $str1 .= "{$yeji},";
                    }elseif ($count-1==$k){
                        $yeji = $v['performance']/10000;
                        $str .="'{$v['truename']}'";
                        $str1 .= "{$yeji}";
                    }
                }
            }

            $danwei = "万";
        }else{
            if(I("post.months") !="")
            {

                $i_month = I("post.months");

                $i_month_begin = $i_month."-01-01";

                $i_month_end = $i_month."-12-31";

                $sql = "select a.performance,d.department from `qp_department` as d LEFT JOIN 
(select SUM(`performance`) as performance,department_id from qp_performance where compact_time > '$i_month_begin' and compact_time < '$i_month_end'
GROUP BY department_id) as a on d.id = a.department_id order by a.performance desc";

            }else{
                $sql = "select a.performance,d.department from `qp_department` as d LEFT JOIN 
(select SUM(`performance`) as performance,department_id from qp_performance where YEAR(compact_time) = YEAR(now()) 
GROUP BY department_id) as a on d.id = a.department_id order by a.performance desc";
            }

            $list = M()->query($sql);
            $str = "";
            $str1 = "";
            $count = count($list);
            if(!empty($list)){
                foreach($list as $k=>$v){
                    if($count-1>$k){
                        $yeji = $v['performance']/10000;
                        $str.="'{$v['department']}',";
                        $str1 .= "{$yeji},";
                    }elseif ($count-1==$k){
                        $yeji = $v['performance']/10000;
                        $str.="'{$v['department']}'";
                        $str1 .= "{$yeji}";
                    }
                }
            }

            $danwei = "万";
        }
        $z = date('Y');
        $days = '';
        for($i=10;$i>-1;$i--){
            $a = $z-$i;
            if($i_month !=""){
                if($i_month == $a){
                    $days.="<option value='$a' selected='selected'>$a</option>";
                }else{
                    $days.="<option value='$a'>$a</option>";
                }
            }else{
                if($z==$a){
                    $days.="<option value='$a' selected='selected'>$a</option>";
                }else{
                    $days.="<option value='$a'>$a</option>";
                }
            }


        }
        $sel = "<select name='months'>$days</select>";
        //echo $sel;
        $this->assign('title','年度业绩');
        $this->assign("sel_month",$sel);
        $this->assign("contro",'year');
        $this->assign('danwei',$danwei);
        $this->assign('str',$str);
        $this->assign('str1',$str1);
        $this->display('dayPerformanceList');
    }

    function daysInmonth($year='',$month=''){
        if(empty($year)) $year = date('Y');
        if(empty($month)) $month = date('m');
        if (in_array($month, array(1, 3, 5, 7, 8, '01', '03', '05', '07', '08', 10, 12))) {
            $text = '31';        //月大
        }elseif ($month == 2 || $month == '02'){
            if ( ($year % 400 == 0) || ( ($year % 4 == 0) && ($year % 100 !== 0) ) ) {   //判断是否是闰年
                $text = '29';        //闰年2月
            } else {
                $text = '28';        //平年2月
            }
        } else {
            $text = '30';            //月小
        }

        return $text;
    }
}